server:
  port: 80



#person:
#  lastname: zc
#  age: 22
#  boss: false
#  birth: 2018/2/2
#  maps: {k1: v1,k2: v2}
#  lists:
#  - lisi
#  - zhaoliu
#  - zc
#  - jh
#  dog:
#    name: gg
#    age: 2
